### PR TITLE
Adding the "connection" property

### PR DESCRIPTION
**Pull request by michaelaird**
Fixes https://github.com/auth0/auth0.net/issues/405

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
Thanks for raising @michaelaird! Let me figure out why the circle status is not being reported.

**Comment by damieng** [comment]
Circle doesn't run for external PRs as it includes integration tests with secrets and environments :(

**Comment by stevehobbsdev** [comment]
That's true @damieng, thanks. Does that mean that the status doesn't even get reported though? Or is it just broken?

**Comment by stevehobbsdev** [comment]
@damieng Thanks!

**Pull request merged**
