### PR TITLE
added interfaces for clients

### PR DESCRIPTION
**Pull request by DerKobe**
### Changes

Please describe both what is changing and why this is important. Include:

Added interfaces to all client classes including ManagementApiClient.

### References
N/A

### Testing
No testable code was added, just interfaces.

### Checklist

- [√] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

- [√] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

- [√] All existing and new tests complete without errors

### CODE REVIEW

**Comment by frederikprijck** [comment]
Hi @DerKobe,

Could you please elaborate on the intention of this change?

Thanks.

**Comment by DerKobe** [comment]
We want to not be depended on the class itself but only on the interfaces. Afterall how it is now it violates SOLID's Interface-Segregation-Principle, and it makes it really hard to write unit tests. Right now you have to always do component tests by  mocking the complete HTTP correspondence.

**Comment by frederikprijck** [comment]
Thanks for the explanation. Opening PRs without any context is generally not the most ideal way to communicate.
It helps to understand what the intention is here, even if it might be obvious for some the intention is to stick to SOLID, it might not be the case for others. 

I believe your code shouldn't be dependent on our concrete implementations, but also not on our interfaces. Strictly speaking, I would have the code be dependent on your own abstractions and connect the dots using other patterns.

That said, as I believe using interfaces is always better I am happy to look into this and see if we can merge this.

**Review by frederikprijck — APPROVED** [review]

**Comment by frederikprijck** [comment]
Thanks for the PR!

**Pull request merged**
