### PR TITLE
added missing fields to ClientBase class

### PR DESCRIPTION
**Pull request by SebaAnhalt**
Fixing problems while create or update client settings in a tenant

### CODE REVIEW

**Comment by jerriep** [comment]
Thank you for the contribution @SebaAnhalt

**Comment by SebaAnhalt** [comment]
@jerriep Thanks for the quick processing. Do you build a new nuget package with this fix. Maybe 5.1.1 as a hot fix ? :-) https://www.nuget.org/packages/Auth0.ManagementApi/

**Comment by jerriep** [comment]
I hope to release 5.2 later today. Will add endpoints for managing email templates, as well as your fix.

**Comment by jerriep** [comment]
@SebaAnhalt I pushed 5.2.0 to NuGet. Packages should be indexed and available to install in about 10-20 minutes

**Comment by SebaAnhalt** [comment]
@jerriep I´ve just updated the nuget package to 5.2.0. You made my day :-)

**Pull request merged**
