### PR TITLE
Add token_lifetime_for_web to ResourceServerBase

### PR DESCRIPTION
**Pull request by barclayadam**
Adds a missing property from /resource-servers API endpoint

### CODE REVIEW

**Comment by dmarjoram** [comment]
Also needed this, thanks

**Comment by dmarjoram** [comment]
An word on an updated build / nuget package? Thanks

**Comment by luisrudge** [comment]
@dmarjoram It's coming! We're changing the release process, but I think we'll have something out by the end of this week. Sorry to keep you waiting.

**Comment by damieng** [comment]
Shipped in 5.11.0 (out now)

**Pull request merged**
